### PR TITLE
Race Condition Bug Fixes

### LINKED ISSUE #21: Persist the logs of the execution runs.
The logs are in the job pod that executes the Terraform plan and apply. The logs should be stored as a separate entity so they can be viewed after the container is removed. 

Additionally, if the auto-apply is set to false, we should also store the plan file on an entity that out lives the job pod.

### PR DESCRIPTION
**Pull request by luthermonson**
Added/Updated some tffy commands and moved run hash to the state to help with race conditions. Closes #21

### CODE REVIEW

File: pkg/cli/cmds/executions.go [hunk 1]
```diff
@@ -29,11 +30,18 @@ func ExecutionCommand() cli.Command {
...
 			},
 			{
-				Name:      "delete",
-				Aliases:   []string{"del"},
-				Usage:     "Delete executions for a specific state.",
-				ArgsUsage: "[EXECUTION NAME]",
-				Action:    executionDelete,
+				Name:      "prune",
+				Aliases:   []string{"pr"},
+				Usage:     "Takes a state and deletes executions and leaving anything < 7days old, pass --days to change how many days to leave",
```
Comment (rmweir) [inline pkg/cli/cmds/executions.go]: did you mean "leaves anything"?

File: pkg/cli/cmds/executions.go [hunk 2]
```diff
@@ -124,6 +151,36 @@ func executionDelete(c *cli.Context) error {
...
+
+	name := c.Args().First()
+
+	controllers, err := getControllers(kubeConfig, namespace)
+	if err != nil {
+		return err
+	}
+
+	_, err = controllers.executions.Get(namespace, name, metav1.GetOptions{})
+	if err != nil {
```
Comment (rmweir) [inline pkg/cli/cmds/executions.go]: nit: this and the following can be of the form:
`if _, err = controllers.executions.Get(namespace, name, metav1.GetOptions{}); err !=nil `

File: pkg/cli/cmds/states.go [hunk 3]
```diff
@@ -236,14 +236,16 @@ func runState(c *cli.Context) error {
 
 	state, err := getState(namespace, kubeConfig, name)
 	if err != nil {
+		logrus.Debug(err)
```
Comment (rmweir) [inline pkg/cli/cmds/states.go]: should this log as an error?

File: pkg/terraform/state/deploy.go [hunk 4]
```diff
@@ -8,12 +8,13 @@ import (
 	"encoding/json"
 	"fmt"
 
+	"github.com/rancher/terraform-controller/pkg/digest"
+
```
Comment (rmweir) [inline pkg/terraform/state/deploy.go]: are the imports like this deliberately?

File: pkg/terraform/state/handler.go [hunk 5]
```diff
@@ -76,136 +74,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
-		if obj.Status.ExecutionName != runName {
-			obj.Status.ExecutionName = runName
-			return h.states.Update(obj)
-		}
+	//running an execution
+	obj.Status.LastRunHash = runHash
+	obj, err = h.states.Update(obj)
+	if err != nil {
+		logrus.Debug(err)
+		return obj, nil
```
Comment (rmweir) [inline pkg/terraform/state/handler.go]: do you want to return nil on this?

File: pkg/cli/cmds/executions.go [hunk 6]
```diff
@@ -114,6 +138,9 @@ func executionDelete(c *cli.Context) error {
 	}
 
 	for _, exec := range execs.Items {
+		if exec.CreationTimestamp.After(from) {
+			continue
+		}
 		err := controllers.executions.Delete(namespace, exec.Name, &metav1.DeleteOptions{})
 		logrus.Info("deleting " + exec.Name)
```
Comment (rmweir) [inline pkg/cli/cmds/executions.go]: nit: could probably put this above delete

File: pkg/terraform/state/deploy.go (hunk 4 above)
Comment (luthermonson) [reply pkg/terraform/state/deploy.go]: needs fixing.

File: pkg/cli/cmds/executions.go (hunk 6 above)
Comment (luthermonson) [reply pkg/cli/cmds/executions.go]: fixing

File: pkg/terraform/state/handler.go (hunk 5 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: part of the race condition problem. this is a way to try and lock the state before kicking off the job

**Comment by rmweir** [comment]
LGTM

File: pkg/terraform/state/handler.go [hunk 7]
```diff
@@ -76,136 +73,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
-				return obj, errors.WithMessage(err, "updating execution on state change")
-			}
-		}
-		v1.ExecutionConditionDestroyJobDeployed.True(obj)
-		return h.states.Update(obj)
-	})
+	runHash := createRunHash(obj, input, ActionDestroy)
+	if runHash == obj.Status.LastRunHash {
+		logrus.Debug("hashes the same, nothing to do")
+		return obj, fmt.Errorf("job already running %s", obj.Status.LastRunHash)
```
Comment (dramich) [inline pkg/terraform/state/handler.go]: Do you catch this and set the StateConditionJobDeployed condition?

Comment (dramich) [reply pkg/terraform/state/handler.go]: Also curious why the error, won't an error cause it to come back through the controller or does OnRemove not work that way in wrangler

File: pkg/terraform/state/handler.go [hunk 8]
```diff
@@ -76,136 +73,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
-// terraform destroy was run so the state can be requeued for deletion.
-func (h *handler) watchDestroyRun(state *v1.State, execution *v1.Execution) {
+func (h *handler) watchExecution(state *v1.State, execution *v1.Execution, action string) {
+	logrus.Debugf("About to watch %s", execution.Name)
+	maxIterations := 450 //15min
+	i := 0
 	for {
-		logrus.Debugf("Waiting for %s destroy job.", state.Name)
+		logrus.Debugf("Waiting for execution %s.", execution.Name)
+		if maxIterations < i {
```
Comment (dramich) [inline pkg/terraform/state/handler.go]: Is this backwords? should it be `>`?

File: pkg/terraform/state/handler.go [hunk 9]
```diff
@@ -76,136 +73,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
-	return h.states.Update(obj)
+	return obj, fmt.Errorf("watching execution to complete")
 }
 
-// watchDestroyRun checks the execution for the Applied condition, once set
-// terraform destroy was run so the state can be requeued for deletion.
-func (h *handler) watchDestroyRun(state *v1.State, execution *v1.Execution) {
+func (h *handler) watchExecution(state *v1.State, execution *v1.Execution, action string) {
+	logrus.Debugf("About to watch %s", execution.Name)
+	maxIterations := 450 //15min
```
Comment (dramich) [inline pkg/terraform/state/handler.go]: just write a normal for loop, no reason to create all the same vars outside the loop.

File: pkg/terraform/state/handler.go [hunk 10]
```diff
@@ -76,136 +73,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
+			v1.StateConditionJobDeployed.False(currentState)
+			currentState.Status.ExecutionName = ""
+			if ActionDestroy == action {
+				logrus.Debug("Setting Destroyed Condition")
+				v1.StateConditionDestroyed.True(currentState)
+			}
+
+			_, err = h.states.Update(currentState)
+			if err != nil {
+				logrus.Debug("error updating after watching")
```
Comment (dramich) [inline pkg/terraform/state/handler.go]: Maybe this shouldn't be a debug? also, use `Debugf` instead of two logs

File: pkg/cli/cmds/executions.go [hunk 11]
```diff
@@ -124,6 +151,36 @@ func executionDelete(c *cli.Context) error {
...
+		return err
+	}
+
+	err = controllers.executions.Delete(namespace, name, &metav1.DeleteOptions{})
+
+	if err != nil {
+		return err
+	}
+
+	fmt.Printf("Deleted %s\n", name)
```
Comment (dramich) [inline pkg/cli/cmds/executions.go]: Random print

File: pkg/terraform/state/gather.go [hunk 12]
```diff
@@ -119,15 +118,11 @@ func (h *handler) getExecutions(ns string, spec v1.StateSpec) (map[string]string
 func (h *handler) getEnvVars(ns string, spec v1.StateSpec) ([]coreV1.EnvVar, bool, error) {
 	result := []coreV1.EnvVar{}
 
-	logrus.Debugf("Pulling Vars from Secrets: %d", len(spec.Variables.EnvSecretNames))
```
Comment (dramich) [inline pkg/terraform/state/gather.go]: Why drop all debug logs?

File: pkg/terraform/state/handler.go [hunk 13]
```diff
@@ -76,136 +73,178 @@ func (h *handler) OnChange(key string, obj *v1.State) (*v1.State, error) {
...
+		obj.Spec.Version = 1
+	}
+	if obj.Spec.Image == "" {
+		obj.Spec.Image = fmt.Sprintf("%s:latest", DefaultExecutorImage)
+	}
 
+	//new execution if none running
+	exec, err := h.deployCreate(obj, input)
 	if err != nil {
+		logrus.Debug(err)
```
Comment (dramich) [inline pkg/terraform/state/handler.go]: A debug log should have some context, random errors will be hard to trace

File: pkg/cli/cmds/executions.go [hunk 14]
```diff
@@ -3,8 +3,9 @@ package cmds
 import (
 	"encoding/base64"
 	"fmt"
+	"time"
 
-	"github.com/rancher/terraform-controller/pkg/age"
+	"github.com/docker/go-units"
```
Comment (dramich) [inline pkg/cli/cmds/executions.go]: Is this used?

File: pkg/cli/cmds/executions.go (hunk 11 above)
Comment (luthermonson) [reply pkg/cli/cmds/executions.go]: it tells you the delete was successful when you use the cli, why is it random?

File: pkg/terraform/state/handler.go (hunk 10 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: agreed, updated to Errorf

File: pkg/terraform/state/handler.go (hunk 8 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: max is 450, i starts a 0. if i goes over 450 you want it to circuit break. however, a normal for loop in your next comment would also not make this necessary. however... this whole watcher is going away we are going to use an execution controller with issue #44  and put this functionality in an onchange so i dont really want to do any extra work on this guy but could be convinced if you think it's important.

File: pkg/terraform/state/handler.go (hunk 9 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: agree, but it's going away, see comment above

File: pkg/terraform/state/handler.go (hunk 7 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: yes, you want that. everything in OnRemove has to send back an error or it will remove the finalizer and kill the CRD. you can only return nil when for sure the object is ready to be completely removed so you have to just consistently send errors back until the job has completed and run the destroy.

File: pkg/terraform/state/gather.go (hunk 12 above)
Comment (luthermonson) [reply pkg/terraform/state/gather.go]: hrm, thought i wrote a comment on this... i moved on to not debugging this part any more and it was pretty consistent so i dropped the debug as it was too spammy while testing other things.

File: pkg/terraform/state/handler.go (hunk 13 above)
Comment (luthermonson) [reply pkg/terraform/state/handler.go]: agreed added context.

File: pkg/cli/cmds/executions.go (hunk 14 above)
Comment (luthermonson) [reply pkg/cli/cmds/executions.go]: yup in the cli execution list to show when the execution was created

Comment (dramich) [reply pkg/cli/cmds/executions.go]: It should have an alias name then, use goimports to format

**Comment by cjellick** [comment]
lgtm
